######
 GET http://localhost:8080/mywebfluxapp/persons/flux/

###
 GET http://localhost:8080/mywebfluxapp/persons/flux/ages/25

###
 GET http://localhost:8080/mywebfluxapp/persons/flux/names/irina

###
 GET http://localhost:8080/mywebfluxapp/persons/mono?idparam=2

###
 GET http://localhost:8080/mywebfluxapp/persons/mono/4

###

POST http://localhost:8080/mywebfluxapp/add
Content-Type: application/json

{
  "id": 100,
  "age": 26,
  "name": "Leva"
}
